# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_definition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_definition.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18message_definition.proto\" \n\tYGRequest\x12\x13\n\x0breq_message\x18\x01 \x01(\t\"!\n\nYGResponse\x12\x13\n\x0bres_message\x18\x01 \x01(\t24\n\rYGTestService\x12#\n\x08SayHello\x12\n.YGRequest\x1a\x0b.YGResponseb\x06proto3'
)




_YGREQUEST = _descriptor.Descriptor(
  name='YGRequest',
  full_name='YGRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_message', full_name='YGRequest.req_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=60,
)


_YGRESPONSE = _descriptor.Descriptor(
  name='YGResponse',
  full_name='YGResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res_message', full_name='YGResponse.res_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['YGRequest'] = _YGREQUEST
DESCRIPTOR.message_types_by_name['YGResponse'] = _YGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

YGRequest = _reflection.GeneratedProtocolMessageType('YGRequest', (_message.Message,), {
  'DESCRIPTOR' : _YGREQUEST,
  '__module__' : 'message_definition_pb2'
  # @@protoc_insertion_point(class_scope:YGRequest)
  })
_sym_db.RegisterMessage(YGRequest)

YGResponse = _reflection.GeneratedProtocolMessageType('YGResponse', (_message.Message,), {
  'DESCRIPTOR' : _YGRESPONSE,
  '__module__' : 'message_definition_pb2'
  # @@protoc_insertion_point(class_scope:YGResponse)
  })
_sym_db.RegisterMessage(YGResponse)



_YGTESTSERVICE = _descriptor.ServiceDescriptor(
  name='YGTestService',
  full_name='YGTestService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='YGTestService.SayHello',
    index=0,
    containing_service=None,
    input_type=_YGREQUEST,
    output_type=_YGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_YGTESTSERVICE)

DESCRIPTOR.services_by_name['YGTestService'] = _YGTESTSERVICE

# @@protoc_insertion_point(module_scope)
